version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: webhook-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: webhook_db
      POSTGRES_USER: webhookuser
      POSTGRES_PASSWORD: webhookpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U webhookuser -d webhook_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: webhook-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE: postgresql://webhookuser:webhookpass@db:5432/webhook_db
      PORT: 3000
      APP_SECRET: your-secret-key-change-in-production
      WEBHOOK_SECRET: your-webhook-secret
      MAX_EVENTS_PER_PAGE: 50
    ports:
      - "3000:3000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://localhost:3000/health || exit 1",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
